// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsLauMMFU83IT6OZHjOEcGg1nstcv-1lo',
    appId: '1:52018672675:web:169ea892540a9652f2ed96',
    messagingSenderId: '52018672675',
    projectId: 'pulsetask-2346c',
    authDomain: 'pulsetask-2346c.firebaseapp.com',
    storageBucket: 'pulsetask-2346c.firebasestorage.app',
    measurementId: 'G-N75GN94MRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ofqDOwQ6RyFR8VsvNjBeZA3M49dhWYs',
    appId: '1:52018672675:android:ceffe5e180399d23f2ed96',
    messagingSenderId: '52018672675',
    projectId: 'pulsetask-2346c',
    storageBucket: 'pulsetask-2346c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeTljsa7hfozTCcsZGivpqRHwQVGiePwc',
    appId: '1:52018672675:ios:a73b74a493ba5ff6f2ed96',
    messagingSenderId: '52018672675',
    projectId: 'pulsetask-2346c',
    storageBucket: 'pulsetask-2346c.firebasestorage.app',
    iosBundleId: 'com.example.pulseTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeTljsa7hfozTCcsZGivpqRHwQVGiePwc',
    appId: '1:52018672675:ios:a73b74a493ba5ff6f2ed96',
    messagingSenderId: '52018672675',
    projectId: 'pulsetask-2346c',
    storageBucket: 'pulsetask-2346c.firebasestorage.app',
    iosBundleId: 'com.example.pulseTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsLauMMFU83IT6OZHjOEcGg1nstcv-1lo',
    appId: '1:52018672675:web:41fab66b5a01609bf2ed96',
    messagingSenderId: '52018672675',
    projectId: 'pulsetask-2346c',
    authDomain: 'pulsetask-2346c.firebaseapp.com',
    storageBucket: 'pulsetask-2346c.firebasestorage.app',
    measurementId: 'G-P3YYDQCH8C',
  );
}
