// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMQmMA3YAAnYim4m4K1hkJf7h2c_nsBI8',
    appId: '1:309551421001:web:275dfb9899c3ef81209198',
    messagingSenderId: '309551421001',
    projectId: 'pulse-task',
    authDomain: 'pulse-task.firebaseapp.com',
    storageBucket: 'pulse-task.firebasestorage.app',
    measurementId: 'G-6ZE2PW307Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB78Ma8VAAVYPlc-LPB4g-YA3e-gyYrDXY',
    appId: '1:309551421001:android:a20e9c95ab492057209198',
    messagingSenderId: '309551421001',
    projectId: 'pulse-task',
    storageBucket: 'pulse-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY_aMrSSplO9fPq2d1XEXlGErg3jLlPPM',
    appId: '1:309551421001:ios:7531691953768e80209198',
    messagingSenderId: '309551421001',
    projectId: 'pulse-task',
    storageBucket: 'pulse-task.firebasestorage.app',
    iosBundleId: 'com.gabrieleduardo.pulsetask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY_aMrSSplO9fPq2d1XEXlGErg3jLlPPM',
    appId: '1:309551421001:ios:813c8cabbe8a397e209198',
    messagingSenderId: '309551421001',
    projectId: 'pulse-task',
    storageBucket: 'pulse-task.firebasestorage.app',
    iosBundleId: 'com.example.pulseTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMQmMA3YAAnYim4m4K1hkJf7h2c_nsBI8',
    appId: '1:309551421001:web:cefe55162cd61749209198',
    messagingSenderId: '309551421001',
    projectId: 'pulse-task',
    authDomain: 'pulse-task.firebaseapp.com',
    storageBucket: 'pulse-task.firebasestorage.app',
    measurementId: 'G-SSY0DB3HFV',
  );

}